### ISSUE TITLE
yarn db:migrate exception (deploy server error)

### ISSUE THREAD

**Issue by Jafee** [0xProject/0x-api#1144]
This problem only appeared after the latest update

Ubuntu 22.04 LTS
node version: v16.18.1
yarn version: 1.22.19

1. edit `.env` file, update `CHAIN_ID`, `ETHEREUM_RPC_URL` and `POSTGRES_URI`
2. `yarn`
3. `yarn build`
4. `docker compose up`
5. `yarn db:migrate`

```
Error during migration run:
MissingDriverError: Wrong driver: "undefined" given. Supported drivers are: "cordova", "expo", "mariadb", "mongodb", "mssql", "mysql", "oracle", "postgres", "sqlite", "better-sqlite3", "sqljs", "react-native", "aurora-data-api", "aurora-data-api-pg".
    at new MissingDriverError (/root/0x-api/node_modules/typeorm/error/MissingDriverError.js:10:28)
    at DriverFactory.create (/root/0x-api/node_modules/typeorm/driver/DriverFactory.js:67:23)
    at new Connection (/root/0x-api/node_modules/typeorm/connection/Connection.js:53:59)
    at ConnectionManager.create (/root/0x-api/node_modules/typeorm/connection/ConnectionManager.js:56:26)
    at Object.<anonymous> (/root/0x-api/node_modules/typeorm/index.js:195:66)
    at step (/root/0x-api/node_modules/tslib/tslib.js:141:27)
    at Object.next (/root/0x-api/node_modules/tslib/tslib.js:122:57)
    at /root/0x-api/node_modules/tslib/tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/root/0x-api/node_modules/tslib/tslib.js:111:16)
    at Object.createConnection (/root/0x-api/node_modules/typeorm/index.js:180:20)
    at Object.<anonymous> (/root/0x-api/node_modules/typeorm/commands/MigrationRunCommand.js:62:54)
    at step (/root/0x-api/node_modules/tslib/tslib.js:141:27)
    at Object.next (/root/0x-api/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/root/0x-api/node_modules/tslib/tslib.js:112:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by Jafee** [comment]
@kyu-c please pay attention to this issue.

**Comment by kyu-c** [comment]
Likely you won't need a postgres. I suggest not specifying `POSTGRES_URI` and not running `yarn db:migrate`

**Comment by Jafee** [comment]
@kyu-c 

when specifying POSTGRES_URI=postgres://api:api@localhost/api in `.env`, throw the same error.

You can try to deploy according to the readme document, but it can't work normally.




> Likely you won't need a postgres. I suggest not specifying `POSTGRES_URI` and not running `yarn db:migrate`

Does HTTP Service not need a relational database?

**Comment by justincavery** [comment]
@Jafee  This was fixed by adding "module.exports = config;" at the end in file src/ormconfig.ts

solution thanks to https://github.com/0xProject/0x-api/issues/1157#issuecomment-1384318799
