### ISSUE TITLE
Getting - MissingDriverError: Wrong driver: "undefined" while forking 0x-api and running yarn db:migrate

### ISSUE THREAD

**Issue by 0xsatya** [0xProject/0x-api#1157]
## Expected Behavior

I am just trying to run 0x-api locally on my mac and on AWS server. I just forked the 0x-api repo and followed instructions in README.md for Getting Started, but installation is not happening as expected and I am getting error while executing ```yarn db:migrate``` command

## Current Behavior

```yarn db:migrate``` is throwing following error -
```
$ yarn db:migrate
yarn run v1.22.19
$ ./node_modules/.bin/typeorm migration:run --config ./lib/src/ormconfig.js 
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
Error during migration run:
MissingDriverError: Wrong driver: "undefined" given. Supported drivers are: "cordova", "expo", "mariadb", "mongodb", "mssql", "mysql", "oracle", "postgres", "sqlite", "better-sqlite3", "sqljs", "react-native", "aurora-data-api", "aurora-data-api-pg".
    at new MissingDriverError (/Users/.../0xProject/0x-api/node_modules/typeorm/error/MissingDriverError.js:10:28)
    at DriverFactory.create (/Users/.../0xProject/0x-api/node_modules/typeorm/driver/DriverFactory.js:67:23)
    at new Connection (/Users/.../0xProject/0x-api/node_modules/typeorm/connection/Connection.js:53:59)
    at ConnectionManager.create (/Users/.../0xProject/0x-api/node_modules/typeorm/connection/ConnectionManager.js:56:26)
    at Object.<anonymous> (/Users/.../0xProject/0x-api/node_modules/typeorm/index.js:195:66)
```

## Steps to Reproduce (for bugs)
```
1. $ git clone https://github.com/0xProject/0x-api.git
2. Updated Required and REcommended params of .env file
3. Updated POSTGRES_URI=postgresql://api:api@localhost/api
4. Followed steps in Getting started and run following commands in terminal
5. $ yarn
6. $ yarn build
7. $ docker-compose up
8. $ yarn db:migrate
9. I haven't changed/updated any other config files of the project.
```

## Context

Due to above problem, I am not able to run 0x-api locally or on my private server and not able to further implement the expected use case required for my project.

## Your Environment
1. OS - mac, apple silicon chip
2. node -v
v16.13.2
3. $ docker -v
Docker version 20.10.21, build baeda1f
4. yarn -v
1.22.19

**Comment by sentienceai** [comment]
Hi @justincavery .. I could resolve the issue by adding "module.exports = config;" at the end in file src/ormconfig.ts

**Comment by 0xsatya** [comment]
Hi @justincavery.. I could resolve the issue by adding "module.exports = config;" at the end in file src/ormconfig.ts

**Comment by justincavery** [comment]
> Hi @justincavery.. I could resolve the issue by adding "module.exports = config;" at the end in file src/ormconfig.ts

That worked for me as well in getting past that error.

Now I'm getting this one https://github.com/0xProject/0x-api/issues/896

**Comment by justincavery** [comment]
Also @0xsatya do you want to close this issue and label your own answer as resolved?

**Comment by justincavery** [comment]
The `db:migrate` was able to run fine with your update on a fresh install.

Once the db:migrate runes, if I do `yarn start` I get back 

```bash
{"level":"error","time":1674054987410,"pid":106704,"hostname":"nftx-0x-api-arbitrum","msg":"TypeError: (0 , ormconfig_1.getOrmConfig) is not a function\n    at getDBConnection (/root/0x-api/lib/src/db_connection.js:11:52)\n    at getDefaultAppDependenciesAsync (/root/0x-api/lib/src/runners/utils.js:94:66)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /root/0x-api/lib/src/index.js:11:30"}
```
