### ISSUE TITLE
The Ganache chain is not support, can we have that support?

### ISSUE THREAD

**Issue by devzyf** [0xProject/0x-api#314]
Error during migration run:
events-pipeline_1  | Error: Chain ID 1337 is not supported. Please choose a valid Chain ID: 1,3,4,42
events-pipeline_1  |     at throwError (/usr/src/app/lib/src/config.js:5:11)
events-pipeline_1  |     at Object.<anonymous> (/usr/src/app/lib/src/config.js:36:5)
events-pipeline_1  |     at Module._compile (internal/modules/cjs/loader.js:816:30)
events-pipeline_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
events-pipeline_1  |     at Module.load (internal/modules/cjs/loader.js:685:32)
events-pipeline_1  |     at Function.Module._load (internal/modules/cjs/loader.js:620:12)
events-pipeline_1  |     at Module.require (internal/modules/cjs/loader.js:723:19)
events-pipeline_1  |     at require (internal/modules/cjs/helpers.js:14:16)
events-pipeline_1  |     at Object.<anonymous> (/usr/src/app/lib/src/ormconfig.js:3:16)
events-pipeline_1  |     at Module._compile (internal/modules/cjs/loader.js:816:30)

**Comment by natewill** [comment]
Did you fix it?
