### ISSUE TITLE
Running 0xorg/0x-api fails with: Cannot read property 'subscription' of undefined

### ISSUE THREAD

**Issue by manolodewiner** [0xProject/0x-api#524]
## Expected Behavior

`0xorg/0x-api` https://hub.docker.com/layers/0xorg/0x-api/latest/images/sha256-91f854b47cb6e1f1efe8046acd6b8a0581867adb1a78aa7466f09449cab0364f?context=explore
works properly
## Current Behavior

I'm getting the following error
```
WARNING: Multiple definitions for safeTransferFrom
{"level":"info","time":1616768740399,"pid":1,"hostname":"ae09c5ab7a52","msg":"OrderWatcherService starting up!","v":1}
{"level":"info","time":1616768740400,"pid":1,"hostname":"ae09c5ab7a52","msg":"OrderWatcherService syncing orderbook with Mesh","v":1}
{"level":"info","time":1616768740414,"pid":1,"hostname":"ae09c5ab7a52","msg":"server listening on 3000","v":1}
{"level":"error","time":1616768740445,"pid":1,"hostname":"ae09c5ab7a52","msg":"Cannot read property 'subscription' of undefined","stack":"TypeError: Cannot read property 'subscription' of undefined\n    at WebsocketProvider.onMessage (/usr/src/app/node_modules/web3-providers/dist/web3-providers.cjs.js:331:59)\n    at WebsocketProvider.onMessage (/usr/src/app/node_modules/web3-providers/dist/web3-providers.cjs.js:470:77)\n    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/usr/src/app/node_modules/yaeti/lib/EventTarget.js:115:12)\n    at W3CWebSocket.onMessage (/usr/src/app/node_modules/web3-providers/node_modules/websocket/lib/W3CWebSocket.js:246:18)\n    at WebSocketConnection.<anonymous> (/usr/src/app/node_modules/web3-providers/node_modules/websocket/lib/W3CWebSocket.js:205:19)\n    at WebSocketConnection.emit (events.js:314:20)\n    at WebSocketConnection.processFrame (/usr/src/app/node_modules/web3-providers/node_modules/websocket/lib/WebSocketConnection.js:531:26)\n    at /usr/src/app/node_modules/web3-providers/node_modules/websocket/lib/WebSocketConnection.js:323:40\n    at processTicksAndRejections (internal/process/task_queues.js:79:11)","type":"Error","v":1}
```

## Steps to Reproduce (for bugs)

Running:
- 0xorg/0x-api (latest)
- Mesh v11.0.2 and 0x-mesh master branch (tried with both)
- Postgres 9.6
- ETH rpc: Infura (Kovan and mainnet, tried both)

Running the docker image with proper `MESH_WEBSOCKET_URI` and `ETHEREUM_RPC_URL` fails.

**Comment by opaolini** [comment]
Is your `ETHEREUM_RPC_URL` a `wss://` or an `https://` URL?

**Comment by opaolini** [comment]
You're using a `v3-frozen` version of 0xAPI, you should connect it to Mesh v9 as v11 has a graphql interface.

**Comment by manolodewiner** [comment]
Thanks @opaolini . Okay right that's the issue! Any plans on supporting v3 orders for the graphql interface in the API? As I can see the mast branch of API only supports v4 orders.
