### ISSUE TITLE
yarn dev wrong. Error: API Key  isn't UUID compliant

### ISSUE THREAD

**Issue by yanyanho** [0xProject/0x-api#559]
## Steps to Reproduce (for bugs)

```
1.
2.
3.
```

**Comment by Eh1Ka6** [comment]
same issue here

**Comment by Eh1Ka6** [comment]
Hey,  
It seems the problem is caused by this INTEGRATOR_ACL option when the parameter is left empty. 
If it's a required parameter could you update the doc or leave a word here on how to configure properly this option?

**Comment by GauthamGoli** [comment]
Is there any workaround ?

**Comment by devnullada** [comment]
A workaround is to comment out line 707 in src/config.ts

**Comment by saad3074** [comment]
@Eh1Ka6 @GauthamGoli @yanyanho @devnullada @dekz   I am facing same issue what is the solution for this issue

$ ./node_modules/.bin/typeorm migration:run --config ./lib/src/ormconfig.js 
Error during migration run:
Error: API Key  isn't UUID compliant
    at /home/shaibiii/0x/0x-api/src/config.ts:726:27
    at Array.forEach (<anonymous>)
    at assertEnvVarType (/home/shaibiii/0x/0x-api/src/config.ts:723:21)
    at Object.<anonymous> (/home/shaibiii/0x/0x-api/src/config.ts:314:11)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/home/shaibiii/0x/0x-api/src/ormconfig.ts:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by crypto-date** [comment]
We just submitted a pr that fixes this issue https://github.com/0xProject/0x-api/pull/835

**Comment by samisbakedham** [comment]
> We just submitted a pr that fixes this issue here: #835

Thank you!
