### ISSUE TITLE
Error: API Key  isn't UUID compliant

### ISSUE THREAD

**Issue by surajit2608** [0xProject/0x-api#785]
/var/www/0x-api/src/config.ts:727
            apiKeys.forEach((apiKey) => {
                    ^
Error: API Key  isn't UUID compliant
    at /var/www/0x-api/src/config.ts:730:27
    at Array.forEach (<anonymous>)
    at assertEnvVarType (/var/www/0x-api/src/config.ts:727:21)
    at Object.<anonymous> (/var/www/0x-api/src/config.ts:314:11)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module.m._compile (/var/www/0x-api/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (/var/www/0x-api/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/var/www/0x-api/src/app.ts:18:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module.m._compile (/var/www/0x-api/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by crypto-date** [comment]
We just submitted a PR that fixes this issue here: https://github.com/0xProject/0x-api/pull/835. The other workaround is to create a uuid and set it to SRA_PERSISTENT_ORDER_POSTING_WHITELISTED_API_KEYS.

**Comment by samisbakedham** [comment]
> 

How do we create a UUID?
